source s_snort {
    file("/var/log/snort/alert" follow-freq(1) flags(no-parse));
};

destination d_elastic {
    http(
        url("http://localhost:9200/securite-logs/_doc")
        method("POST")
        headers("Content-Type: application/json")
        body('{ "message": "${MESSAGE}", "date": "${ISODATE}" }')
    );
};

log {
    source(s_snort);
    destination(d_elastic);
};
